from fastapi import FastAPI
from fastapi.responses import HTMLResponse
import random

app = FastAPI()

insults = [
   "you fucking retarded nigger, go choke on your own stupidity.",
"Pathetic limp-dicked paki bastard, crawl back into whatever shithole you came from.",
"You braindead autistic tranny kike, nobody wants your worthless ass here.",
"You disgusting spic faggot cunt, kill yourself you worthless fuck.",
"You inbred redneck nigger lover, your bloodline is pure garbage.",
"You fat dyke retard, even dogs refuse to fuck you.",
"You slope-eyed chink faggot, go eat bats and die already.",
"You filthy camel jockey sand nigger, fuck off to your desert.",
"You limp-wristed jew faggot, your mother should’ve aborted you.",
"You retarded mongoloid gook, you’re a waste of oxygen.",
"You stupid cum-guzzling nigger bitch, choke on dick and die.",
"You pathetic paki rapist, go fuck your sister you inbred fuck.",
"You autistic tranny freak, cut deeper next time you cunt.",
"You dirty spic wetback, drown in the river you crossed.",
"You hillbilly nigger, your family tree is a straight line.",
"You fat lesbian cunt, no one will ever love your disgusting body.",
"You rice-eyed chink virus carrier, go back to eating dogs.",
"You terrorist towelhead, blow yourself up already you dog.",
"You hook-nosed kike bastard, steal another penny and die.",
"You downie retard faggot, your parents regret not swallowing.",
"You worthless nigger animal, go swing from a tree you ape.",
"You limp-dicked paki groomer, touch kids somewhere else.",
"You brainless tranny abomination, you’ll never be a woman.",
"You greasy spic beaner, go pick fruit you subhuman.",
"You inbred methhead redneck, your sister is your mother.",
"You obese dyke whale, roll back to the sea you fat cunt.",
"You squinty chink spy, go steal more tech you thief.",
"You bomb-making towelhead, Allah is disappointed in your failure.",
"You cheap jew rat, go gas yourself you greedy fuck.",
"You retarded slope gook, your country is a sweatshop.",
"You AIDS-ridden nigger monkey, go spread it somewhere else.",
"You sister-fucking paki goat, your whole family is cursed.",
"You mutilated tranny mistake, kill yourself you freak.",
"You border-hopping spic, get deported you parasite.",
"You cousin-fucking redneck, your IQ is room temperature.",
"You carpet-munching dyke, your pussy smells like death.",
"You bat-eating chink, release the next virus you lab rat.",
"You suicide vest wearing sand nigger, do it properly this time.",
"You penny-pinching kike, your nose is bigger than your dick.",
"You helmet-wearing retard, your parents wish you were dead.",
"You jungle bunny nigger, go back to the zoo.",
"You child-marrying paki, your religion is pure filth.",
"You chopped-dick tranny, you’re still just a man in a dress.",
"You taco-eating wetback spic, learn to speak English you dog.",
"You trailer trash redneck, fuck your sister again.",
"You man-hating fat dyke, no one wants your hairy cunt.",
"You dog-eating chink, your eyes are as small as your brain.",
"You desert rat towelhead, go fuck a camel.",
"You holocaust-denying kike, you deserve the real one.",
"You window-licking mongoloid, drool on your own grave.",
"You nigger loving faggot, your dad is ashamed of you.",
"You paki wife beater, go beat your cousin instead.",
"You fake tranny whore, nobody is buying your delusion.",
"You spic gangbanger, get shot by your own kind.",
"You redneck sister fucker, your kids have birth defects.",
"You bulldyke cunt, your clit is bigger than your brain.",
"You chink bat soup slurper, go die in a wet market.",
"You towelhead terrorist, your bomb failed again.",
"You greedy hooknose kike, count your shekels in hell.",
"You retarded down syndrome faggot, lick the windows harder.",
"You jungle nigger savage, go back to mud huts.",
"You goat fucking paki, your wife is your sister.",
"You dickless tranny, kill yourself you confused cunt.",
"You beaner wetback spic, swim back you illegal fuck.",
"You meth smoking redneck, your teeth are falling out.",
"You hairy armpit dyke, no man will ever touch you.",
"You squinty eyed chink, your dick is as small as your eyes.",
"You sand nigger camel fucker, blow up your own family.",
"You cheap jew bastard, your gold is fake just like you.",
"You helmet head retard, drool more you fucking spastic.",
"You AIDS spreading nigger, infect your whole hood.",
"You child raping paki, your prophet would be proud.",
"You mutilated tranny freak, you’ll never pass.",
"You border jumping spic, steal more jobs you rat.",
"You cousin fucking redneck, your family is disgusting.",
"You fat lesbian whale, go eat another pussy.",
"You dog meat eating chink, your country is a virus factory.",
"You bomb vest towelhead, try harder next time.",
"You greedy kike rat, Auschwitz missed you.",
"You window licking mong, your life is a mistake.",
"You ape nigger, go eat bananas you primate.",
"You inbred paki fuck, your blood is rotten.",
"You fake woman tranny, cut your dick off properly.",
"You taco nigger spic, go back to Mexico you thief.",
"You trailer park redneck, fuck your mom again.",
"You man hating dyke, your pussy is rotten.",
"You virus making chink, Wuhan thanks you.",
"You desert monkey sand nigger, go pray to your rock.",
"You penny stealing jew, your nose reaches your wallet.",
"You braindead retard, your parents should have pulled out.",
"You cotton picking nigger, go pick my balls.",
"You goat herder paki, marry your daughter.",
"You chopped cock tranny, you’re a mental illness.",
"You fence hopping spic, get shot at the border.",
"You sister impregnating redneck, your kids are retarded.",
"You carpet licker dyke, your breath smells like fish.",
"You rice nigger chink, go cough on more people.",
"You suicide bomber towelhead, do the world a favor.",
"You holocaust survivor kike, next time finish the job.",
"You spastic retard, lick the bus windows.",
"You spear throwing nigger, go back to Africa.",
"You cousin bride paki, your genes are fucked.",
"You estrogen filled tranny, you still look like a man.",
"You burrito spic, learn English you dirty fuck.",
"You banjo playing redneck, your sister is pregnant again.",
"You bull dyke cunt, shave your mustache.",
"You bat soup chink, your mother eats rats.",
"You raghead sand nigger, your Allah hates you.",
"You shekel counting jew, go die in Israel.",
"You helmet wearing mongoloid, your brain never grew.",
"You porch monkey nigger, go steal more bikes.",
"You sister fucking paki, your family tree is a circle.",
"You fake tits tranny, nobody wants your fake pussy.",
"You wetback spic, drown next time.",
"You meth head redneck, your teeth are black.",
"You rug munching dyke, your fingers smell like tuna.",
"You corona spreading chink, your lab leaked again.",
"You camel humper towelhead, fuck your goat.",
"You greedy kike, your foreskin is in a jar.",
"You downie faggot, your mom cries every night.",
"You nigger ape, swing from trees you animal.",
"You bomb making paki, your bomb was fake like you.",
"You dick cutting tranny, bleed out you freak.",
"You bean eating spic, go pick tomatoes.",
"You hillbilly redneck, your mom is also your aunt.",
"You fat bulldyke, your cunt has teeth.",
"You eye squinting chink, go steal more secrets.",
"You desert nigger sand monkey, blow yourself up.",
"You cheap jew fuck, your gold teeth are fake.",
"You retarded spastic, your wheelchair is waiting.",
"You cotton field nigger, go shine my shoes.",
"You child bride paki, your prophet is a pedo.",
"You ball chopping tranny, you’re still a dude.",
"You fence climbing spic, get deported you leech.",
"You cousin fucking redneck, your IQ is 50.",
"You pussy licking dyke, your breath is deadly.",
"You dog eating chink, your dick is tiny.",
"You towel head terrorist, your virgins are waiting in hell.",
"You nose hook kike, count money in hell.",
"You brainless retard, your life is pointless.",
"You spear chucking nigger, go back to the jungle.",
"You goat fucking paki, marry your goat.",
"You fake ass tranny, you’ll never be real.",
"You rice stealing spic, go back south of the border.",
"You trailer nigger redneck, fuck your cousin.",
"You man faced dyke, no one wants you.",
"You virus lab chink, Wuhan is proud.",
"You sand rat towelhead, your bomb failed again.",
"You shekel hoarder jew, gas chamber is calling.",
"You window licker retard, drool more.",
"You porch monkey nigger, steal another bike.",
"You inbred paki, your kids have extra fingers.",
"You hormone tranny, your voice is still deep.",
"You taco spic, learn to speak properly.",
"You sister fucker redneck, your family is cursed.",
"You hairy dyke, your armpits smell like shit.",
"You bat eater chink, release another plague.",
"You camel fucker sand nigger, your desert is shit.",
"You greedy jew rat, your bank is fake.",
"You helmet head mong, your brain is smooth.",
"You nigger coon, go pick cotton.",
"You child rapist paki, your religion is sick.",
"You dickless tranny cunt, kill yourself.",
"You illegal spic, swim back you rat.",
"You meth redneck, your teeth fell out.",
"You lesbian whale, go eat more carpet.",
"You squinty chink, your brain is small.",
"You raghead, blow up your mosque.",
"You hooknose kike, your money is blood money.",
"You spastic retard, your parents hate you.",
"You ape nigger, go back to zoo.",
"You goat paki, fuck your animals.",
"You confused tranny, cut deeper.",
"You beaner spic, pick fruit you dog.",
"You banjo redneck, impregnate your sister.",
"You bull dyke, your clit is huge.",
"You dog meat chink, your eyes are slits.",
"You suicide sand nigger, try harder.",
"You cheap jew, die in oven.",
"You downie, your life is joke.",
"You jungle nigger, mud hut awaits.",
"You cousin paki, your blood is bad.",
"You fake woman tranny, man in dress.",
"You wet spic, drown you fuck.",
"You trailer redneck, fuck mom.",
"You fat dyke, hairy cunt.",
"You corona chink, lab leak.",
"You desert towelhead, camel fucker.",
"You shekel kike, greedy rat.",
"You retard mong, drool.",
"You cotton nigger, shine shoes.",
"You pedo paki, child bride.",
"You chopped tranny, bleed out.",
"You border spic, deported.",
"You inbred redneck, sister mom.",
"You carpet dyke, fish smell.",
"You rice chink, tiny dick.",
"You bomb towelhead, fail again.",
"You holocaust kike, missed you.",
"You licker retard, bus windows.",
"You savage nigger, jungle back.",
"You goat paki, marry daughter.",
"You estrogen tranny, still man.",
"You burrito spic, English dog.",
"You meth redneck, black teeth.",
"You armpit dyke, no man.",
"You virus chink, cough more.",
"You humper towelhead, goat fuck.",
"You jew rat, foreskin jar.",
"You spastic, wheelchair.",
"You monkey nigger, bananas.",
"You bride paki, genes fucked.",
"You tits tranny, fake pussy.",
"You fence spic, shot border.",
"You cousin redneck, IQ low.",
"You licker dyke, tuna breath.",
"You soup chink, rats.",
"You vest sand nigger, virgins hell.",
"You counting jew, hell money.",
"You licking retard, pointless life.",
"You chucking nigger, Africa.",
"You herder paki, goat wife.",
"You cock tranny, mental illness.",
"You jumping spic, leech.",
"You fucking redneck, 50 IQ.",
"You munching dyke, deadly breath.",
"You eating chink, tiny dick.",
"You head towelhead, virgins hell.",
"You kike, gas chamber.",
"You retard, parents hate.",
"You nigger, zoo.",
"You paki, extra fingers.",
"You tranny, deep voice.",
"You spic, speak properly.",
"You redneck, cursed family.",
"You dyke, shit armpits.",
"You chink, another plague.",
"You nigger, shit desert.",
"You jew, blood money.",
"You mong, smooth brain.",
"You nigger, pick cotton.",
"You paki, sick religion.",
"You tranny, kill self.",
"You spic, rat swim.",
"You redneck, teeth out.",
"You dyke, eat carpet.",
"You chink, small brain.",
"You towelhead, mosque blow.",
"You kike, blood money.",
"You retard, joke life.",
"You nigger, hut mud.",
"You paki, bad blood.",
"You tranny, dress man.",
"You spic, fuck dog.",
"You redneck, mom sister.",
"You dyke, cunt hairy.",
"You chink, leak lab.",
"You sand nigger, fuck camel.",
"You jew, rat greedy.",
"You retard, drool more.",
"You nigger, shoes shine.",
"You paki, bride child.",
"You tranny, out bleed.",
"You spic, rat you.",
"You redneck, low IQ.",
"You dyke, smell fish.",
"You chink, dick tiny.",
"You towelhead, fail bomb.",
"You kike, oven die.",
"You retard, joke you.",
"You nigger, back jungle.",
"You paki, daughter marry.",
"You tranny, man still.",
"You spic, dog English.",
"You redneck, out teeth.",
"You dyke, man no.",
"You chink, more cough.",
"You towelhead, fuck goat.",
"You jew, jar foreskin.",
"You retard, hate parents.",
"You nigger, bananas eat.",
"You paki, fucked genes.",
"You tranny, pussy fake.",
"You spic, border shot.",
"You redneck, low IQ.",
"You dyke, breath deadly.",
"You chink, rats eat.",
"You sand nigger, hell virgins.",
"You jew, money hell.",
"You retard, life pointless.",

]

@app.get("/", response_class=HTMLResponse)
def roast():
    insult = random.choice(insults)
    return f"""
    <html>
        <head><title>meanie</title></head>
        <body style="background:#111; color:#ff4444; font-family:monospace; 
                     display:flex; align-items:center; justify-content:center; 
                     height:100vh; margin:0; text-align:center; padding:20px;">
            <h1>{insult}</h1>
        </body>
    </html>
    """