from fastapi import FastAPI
from fastapi.responses import HTMLResponse
import random

app = FastAPI()

insults =[
  "You brain-dead walnut, go choke on your own stupidity.",
  "You pathetic limp-dicked loser, crawl back into your mom's basement.",
  "You absolute clown, even your mirror laughs at you.",
  "You worthless waste of oxygen, do the world a favor and disappear.",
  "You smooth-brained idiot, your IQ is lower than room temperature.",
  "You disgusting slob, even cockroaches have better hygiene than you.",
  "You sad excuse for a human, your existence is disappointing.",
  "You pathetic try-hard, nobody cares about your opinions.",
  "You walking L, everything you touch turns into garbage.",
  "You delusional clown, touch grass and get a reality check.",
  "You spineless jellyfish, grow a backbone you weakling.",
  "You annoying little gremlin, go touch some sunlight.",
  "You certified dumbass, your brain is permanently on airplane mode.",
  "You irrelevant nobody, the void is more interesting than you.",
  "You cringy attention whore, log off and touch grass.",
  "You walking disappointment, your parents regret you the most.",
  "You talentless hack, even your excuses are pathetic.",
  "You emotional dumpster fire, seek help instead of attention.",
  "You sad little troll, your life must be painfully empty.",
  "You beta clown, keep coping in your fantasy world.",
  "You useless sack of potatoes, at least potatoes are useful.",
  "You pathetic keyboard warrior, go fail in real life.",
  "You certified failure, even your shadow wants to leave you.",
  "You brainless NPC, get some original thoughts for once.",
  "You disgusting neckbeard, take a shower and fix your life.",
  "You miserable gremlin, your vibe repels normal people.",
  "You absolute joke, comedy shows called and said they're full.",
  "You low-effort loser, even participation trophies reject you.",
  "You sad virgin, your personality is the best contraceptive.",
  "You walking red flag, everyone blocks you for a reason.",
  "You pathetic simp, go touch grass instead of knees.",
  "You chronically online degenerate, log off and rot.",
  "You talentless hack, your dreams are disappointed in you.",
  "You human equivalent of a software bug.",
  "You expired milk of a person, sour and unwanted.",
  "You wet sock in human form, useless and annoying.",
  "You soggy bread excuse of a man.",
  "You unseasoned chicken of a person, bland and disappointing.",
  "You participation trophy of a human being.",
  "You mid-tier nothing, nobody remembers you exist.",
  "You human loading screen, slow and completely pointless.",
  "You glitch in the matrix, annoying and should be patched.",
  "You human equivalent of a 404 error - brain not found.",
  "You warm glass of milk on a summer day, disappointing.",
  "You leftover pizza forgotten in the fridge for 3 weeks.",
  "You default Discord pfp of a person.",
  "You unread notification in human form.",
  "You 'seen at 2:13' energy.",
  "You buffering wheel that never finishes loading.",
  "You Windows Vista of people - slow and outdated.",
  "You human version of Comic Sans.",
  "You low battery warning personified.",
  "You 'this meeting could have been an email' human.",
  "You printer that's always out of ink.",
  "You elevator music of a personality.",
  "You unread email with subject 'URGENT'.",
  "You blue screen of death in human shape.",
  "You laggy video call that keeps freezing.",
  "You expired yogurt of society.",
  "You 'reply all' accident of a person.",
  "You plastic plant - fake and useless.",
  "You knocked over milk - spilled and irrelevant.",
  "You tangled earphone wires of a human.",
  "You '404 brain not found' legend.",
  "You human version of slow internet.",
  "You forgotten browser tab with 47 ads.",
  "You Ctrl+Z that didn’t work.",
  "You autocorrect fail in human form.",
  "You 'yes' man with zero original opinions.",
  "You expired coupon of a person.",
  "You human equivalent of dad jokes.",
  "You participation award collector.",
  "You mid at everything and good at nothing.",
  "You human version of elevator small talk.",
  "You unskippable YouTube ad.",
  "You loading screen that never ends.",
  "You human equivalent of small font terms & conditions.",
  "You 'seen zone' champion.",
  "You human version of 1% battery.",
  "You background noise personified.",
  "You human equivalent of decaf coffee.",
  "You lukewarm water of a personality.",
  "You human version of plain rice.",
  "You 'k' texter in human form.",
  "You human equivalent of a rickroll.",
  "You expired meme.",
  "You human version of Comic Sans on a resume.",
  "You 'read at 3:42am' energy.",
  "You human version of buffering forever.",
  "You stale bread of a human being.",
  "You human equivalent of a broken elevator.",
  "You dusty forgotten shelf of a person.",
  "You human version of pop-up ads.",
  "You expired discount code.",
  "You human equivalent of dial-up internet.",
  "You participation trophy collector.",
  "You human version of a wet blanket.",
  "You sad deflated balloon.",
  "You human equivalent of burnt toast.",
  "You lukewarm disappointment.",
  "You human version of a flat soda.",
  "You walking 'do not disturb' sign.",
  "You human equivalent of small talk at funerals.",
  "You human version of a jammed printer.",
  "You sad little try-hard.",
  "You human equivalent of a Monday morning.",
  "You walking 'out of office' reply.",
  "You human version of a passive-aggressive note.",
  "You sad soggy french fry.",
  "You human equivalent of a parking ticket.",
  "You walking spoiler alert.",
  "You human version of a 3-hour unskippable ad.",
  "You sad little midwit.",
  "You human equivalent of elevator music on hold.",
  "You walking 'seen' message.",
  "You human version of cold coffee.",
  "You sad excuse for ambition.",
  "You human equivalent of a dad joke at a funeral.",
  "You walking participation award.",
  "You human version of a software update at 2am.",
  "You sad little keyboard warrior.",
  "You human equivalent of a group project slacker.",
  "You walking 'reply all' disaster.",
  "You human version of a burnt microwave popcorn.",
  "You sad little try-hard simp.",
  "You human equivalent of a 'thanks in advance' email.",
  "You walking red flag factory.",
  "You human version of a slow zoom call.",
  "You sad little gremlin greeter.",
  "You human equivalent of a 404 page.",
  "You walking disappointment machine.",
  "You human version of plain oatmeal.",
  "You sad little attention beggar.",
  "You human equivalent of a 'k' reply.",
  "You walking mid-life crisis at 22.",
  "You human version of a bad WiFi signal.",
  "You sad little coping mechanism.",
  "You human equivalent of a spoiler in the title.",
  "You walking 'this is fine' dog meme.",
  "You human version of a cheap knockoff.",
  "You sad little main character delusion.",
  "You human equivalent of a 'read the room' failure.",
  "You walking skill issue.",
  "You human version of a loading bar at 99%.",
  "You sad little victim complex.",
  "You human equivalent of a bad haircut.",
  "You walking 'ratio' in human form.",
  "You human version of a cancelled subscription.",
  "You sad little edge-lord.",
  "You human equivalent of a 'sorry not sorry'.",
  "You walking L collector.",
  "You human version of a 'no refunds' policy.",
  "You sad little internet tough guy.",
  "You human equivalent of a ghosted conversation.",
  "You walking 'skill issue' personified.",
  "You human version of a blue screen.",
  "You sad little chronically online loser.",
  "You human equivalent of a 'your opinion is trash' sticker.",
  "You walking disappointment with legs.",
  "You human version of a 'do not reply' email.",
  "You sad little main character syndrome.",
  "You human equivalent of a participation trophy speech.",
  "You walking 'touch grass' violation.",
  "You human version of a 'this could be an email' meeting.",
  "You sad little try-hard edgelord.",
  "You human equivalent of a lukewarm reply.",
  "You walking 'average enjoyer'.",
  "You human version of a 'mid' review.",
  "You sad little 'nobody asked' machine.",
  "You human equivalent of a deleted comment.",
  "You walking copium inhaler.",
  "You human version of a 'ratio + didn't ask'.",
  "You sad little 'main character' wannabe.",
  "You human equivalent of a bad first impression.",
  "You walking skill issue with anxiety.",
  "You human version of a 'thanks for coming to my TED talk'.",
  "You sad little chronically disappointing human.",
  "You human equivalent of a 'seen 8 hours ago'.",
  "You walking 'do better' reminder.",
  "You human version of plain toast with no butter.",
  "You sad little 'I'm not like other guys' guy.",
  "You human equivalent of a 'reply if you see this' post.",
  "You walking midwit with main character syndrome.",
  "You human version of a 'this is why we can't have nice things'.",
  "You sad little 'everyone clapped' liar.",
  "You human equivalent of a 'ratio' in real life.",
  "You walking disappointment generator.",
  "You human version of a 'your mom' joke in 2026.",
  "You sad little 'I'm built different' delusion.",
  "You human equivalent of a 'cringe compilation'.",
  "You walking 'touch some grass' offender.",
  "You human version of a 'didn't read lol'.",
  "You sad little chronically online gremlin.",
  "You human equivalent of a 'mid' tier list.",
  "You walking 'average at best' human.",
  "You human version of a 'skill issue' speedrun.",
  "You sad little 'main character in his own movie' loser.",
  "You human equivalent of a 'reply all' mistake.",
  "You walking 'do the needful' energy.",
  "You human version of a lukewarm take.",
  "You sad little 'I'm 14 and this is deep' philosopher.",
  "You human equivalent of a 'ratio + L + didn't ask'.",
  "You walking 'cope + seethe' machine.",
  "You human version of a 'this meeting could’ve been a DM'.",
  "You sad little chronically disappointing creature.",
  "You human equivalent of a 'your vibes are off' warning.",
  "You walking skill issue with extra steps.",
  "You human version of a 'mid' everything enjoyer.",
  "You sad little 'I'm him' delusion.",
  "You human equivalent of a 'seen zone' champion.",
  "You walking 'touch grass' hypocrite.",
  "You human version of a 'cringe' folder.",
  "You sad little chronically online void.",
  "You human equivalent of a 'ratioed' tweet.",
  "You walking disappointment with wifi.",
  "You human version of a 'this is fine' while burning.",
  "You sad little 'built different' fraud.",
  "You human equivalent of a plain bagel with nothing.",
  "You walking 'average enjoyer' of mediocrity.",
  "You human version of a 'didn't ask + ratio'.",
  "You sad little 'main character syndrome' patient.",
  "You human equivalent of a 'your opinion has been rejected'.",
  "You walking L in human clothing.",
  "You human version of a 'loading...' that never ends.",
  "You sad little 'I'm not like the others' copy-paste.",
  "You human equivalent of a participation award speech.",
  "You walking 'mid' with confidence.",
  "You human version of a 'thanks for nothing'.",
  "You sad little chronically disappointing existence."
]

@app.get("/", response_class=HTMLResponse)
def roast():
    insult = random.choice(insults)
    return f"""
    <html>
        <head><title>meanie</title></head>
        <body style="background:#111; color:#ff4444; font-family:monospace; 
                     display:flex; align-items:center; justify-content:center; 
                     height:100vh; margin:0; text-align:center; padding:20px;">
            <h1>{insult}</h1>
        </body>
    </html>
    """
